FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    pgbouncer \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 6432

USER postgres

CMD ["pgbouncer", "/etc/pgbouncer/pgbouncer.ini"]
